### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by WEOwner** [Viasat/alohomora#37]
trying to use Alohomora with aws cli and duo small and got this error:
Traceback (most recent call last):
  File "/home/UserName/.local/bin/alohomora", line 8, in <module>
    sys.exit(main())
  File "/home/UserName/.local/lib/python2.7/site-packages/alohomora/main.py", line 275, in main
    Main().main()
  File "/home/UserName/.local/lib/python2.7/site-packages/alohomora/main.py", line 193, in main
    (okay, response) = provider.login_two_factor(response, auth_device)
  File "/home/UserName/.local/lib/python2.7/site-packages/alohomora/req.py", line 278, in login_two_factor
    sigs = sig_request.split(':')
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by skemper** [comment]
Hi @WEOwner!  Thanks for the report.  Here are some follow-up questions that can help us understand the bug better:

**Has this SAML setup worked with Alohomora in the past, or is this your first time trying to use it?**
**What SAML Identity Provider (IdP) are you using?** [URL of the service or software package name]
**What installation method did you use to set Duo up with that IdP?** [native support, 3rd-party add on, etc]

**Comment by browseman** [comment]
I'm facing the same issue when tried alohomora. Unfortunately I can't provide details right now, as I don't know the details about the DUO setup.

**Comment by speedwater** [comment]
I'm getting a similar error when attempting to use the URL from a tile in the Duo launcher.  Is there any documentation on an example setup on the Duo side?  Alohomora config documentation is clear, but the expected receiving setup w/in Duo is not.  Thanks!

**Comment by browseman** [comment]
> I'm getting a similar error when attempting to use the URL from a tile in the Duo launcher.

I've followed the same approach of using the URL from the Duo launcher as well.

**Comment by daraclare** [comment]
I have the same issue as the above, in version 3.0.1
